[[plugins]]
repo = 'Shougo/dein.vim'

# カーソル位置のコンテキストに合わせてftを切り替える -- 重すぎるので無効化
#[[plugins]]
#repo = 'osyo-manga/vim-precious'
#depends = ['context_filetype.vim']

[[plugins]]
repo = 'vim-scripts/DirDiff.vim'

# [[plugins]] # カーソル位置のコンテキストのftを判定するライブラリ
# repo = 'Shougo/context_filetype.vim'

# [[plugins]]
# repo = 'delphinus35/typescript-vim'
# rev  = 'colorize-template-strings'
#
# [[plugins]]
# repo = 'kchmck/vim-coffee-script'
#
# [[plugins]]
# repo = 'Shougo/neosnippet-snippets'
#
# [[plugins]]
# repo = 'Shougo/vinarise'

[[plugins]]
repo = 'kshenoy/vim-signature'

[[plugins]]
repo = 'majutsushi/tagbar'

# View and search LSP symbols, tags in Vim/NeoVim.
[[plugins]]
repo = 'liuchengxu/vista.vim'
hook_add = '''
    let g:vista_default_executive = 'vim_lsp'
    function! NearestMethodOrFunction() abort
      return get(b:, 'vista_nearest_method_or_function', '')
    endfunction

    set statusline+=%{NearestMethodOrFunction()}

    " By default vista.vim never run if you don't call it explicitly.
    "
    " If you want to show the nearest function in your statusline automatically,
    " you can add the following line to your vimrc
    autocmd VimEnter * call vista#RunForNearestMethodOrFunction()
'''

[[plugins]]
repo = 'junegunn/fzf'
build = './install --bin'
merged = '0'

[[plugins]]
repo = 'junegunn/fzf.vim'
depends = 'fzf'
hook_add = '''
  command! -bang -nargs=* Rg
    \ call fzf#vim#grep(
    \   'rg --line-number --no-heading '.shellescape(<q-args>), 0,
    \   fzf#vim#with_preview({'options': '--exact --reverse'}, 'right:50%:wrap'))
'''

[[plugins]]
repo = 'kana/vim-operator-user'

# [[plugins]]
# repo = 'rhysd/vim-operator-surround'

# -- git
[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'rhysd/committia.vim'
hook_add = '''
	let g:committia_open_only_vim_starting = 1
	let g:committia_hooks = {}
	function! g:committia_hooks.edit_open(info)
	    " Additional settings
	    setlocal spell

	    " If no commit message, start with insert mode
	    if a:info.vcs ==# 'git' && getline(1) ==# ''
	        startinsert
	    end

	    " Scroll the diff window from insert mode
	    " Map <C-n> and <C-p>
	    imap <buffer><C-n> <Plug>(committia-scroll-diff-down-half)
	    imap <buffer><C-p> <Plug>(committia-scroll-diff-up-half)

	endfunction
'''

[[plugins]]
repo = 'itchyny/vim-gitbranch'

[[plugins]]
repo = 'mhinz/vim-signify'
# --

# [[plugins]]
# repo = 'Shougo/vimfiler'

[[plugins]]
repo = 'Shougo/vimshell'

# -- color scheme
[[plugins]]
repo = 'sheerun/vim-wombat-scheme'

[[plugins]]
repo = 'vim-scripts/wombat256.vim'

[[plugins]]
repo = 'b4b4r07/solarized.vim'
# --

[[plugins]]
repo = 'ujihisa/neco-look'

[[plugins]]
repo = 'Konfekt/FastFold'

[[plugins]]
repo = 'b4b4r07/vim-ansible-vault'

