[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'
on_source = ['unite.vim', 'vimshell.vim']

[[plugins]]
repo = 'elzr/vim-json'
if   = '''! has('kaoriya')'''
on_ft = ['json']
hook_add = '''
let g:vim_json_syntax_conceal = 0
'''

[[plugins]]
repo  = 'Quramy/tsuquyomi'
on_ft = ['typescript']

[[plugins]]
repo = 'simeji/winresizer'
on_event = 'VimEnter'
hook_source = '''
  let g:winresizer_start_key=''
  let g:winresizer_gui_start_key=''
  let g:winresizer_vert_resize=5
  let g:winresizer_horiz_resize=2
'''

[[plugins]]
repo = 'vim-scripts/textutil.vim'
on_ft = ['rtf']

[[plugins]]
repo = 'mechatroner/rainbow_csv'
on_ft= ['csv']

[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft= ['javascript']
hook_source = '''
    let g:javascript_plugin_ngdoc = 1
'''

# {{ markdown
[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = ['markdown']

[[plugins]]
repo = 'godlygeek/tabular'
on_ft = ['markdown']
depends = ['vim-markdown']

[[plugins]]
repo = 'kannokanno/previm'
on_cmd = ['PrevimOpen']
depends = ['open-browser.vim']

[[plugins]]
repo = 'tyru/open-browser.vim'
# }}

[[plugins]]
repo = 'stephpy/vim-yaml'
on_ft = ['yaml']

[[plugins]]
repo = 'lmeijvogel/vim-yaml-helper'
on_ft = ['yaml']

[[plugins]]
repo = 'hashivim/vim-terraform'
on_ft = ['tf','terraform']
hook_source = '''
    let g:terraform_align=1
    let g:terraform_fmt_on_save=1
'''

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

# {{ python
# [[plugins]]
# repo = 'andviro/flake8-vim'
# on_ft = ['python']

#[[plugins]]
#repo = 'hynek/vim-python-pep8-indent'
#on_ft = ['python']
#
#[[plugins]]
#repo = 'tell-k/vim-autopep8'
#on_ft = ['python']
# }}

# {{ ruby
#[[plugins]]
#repo = 'osyo-manga/vim-monster'
#on_ft = ['ruby']
#
#[[plugins]]
#repo = 'marcus/rsense'
#on_ft = ['ruby']
# }}

#[[plugins]]
#repo = 'fatih/vim-go'
#on_ft = ['go']
#hook_source = '''
#	let g:go_highlight_functions = 1
#	let g:go_highlight_methods = 1
#	let g:go_highlight_structs = 1
#  let g:go_highlight_types = 1
#  let g:go_highlight_fields = 1
#  autocmd FileType go :highlight goErr cterm=bold ctermfg=214
#  autocmd FileType go :match goErr /\<err\>/
#'''

# {{ ts
# [[plugins]]
# repo = 'delphinus35/typescript-vim'
# rev  = 'colorize-template-strings'
#
# [[plugins]]
# repo = 'kchmck/vim-coffee-script'
#
# }}

[[plugins]]
repo      = 'thinca/vim-prettyprint'
on_cmd    = ['PP', 'PrettyPrint']

# [[plugins]]
# repo = 'mrtazz/simplenote.vim'
# on_cmd = ['SimplenoteList']

# only for gvim
[[plugins]]
repo   = 'thinca/vim-fontzoom'
on_cmd = ['Fontzoom']
on_map = ['<Plug>(fontzoom-']
gui    = 1

