# lsp related plugins --
[[plugins]]
repo = 'prabirshrestha/async.vim'

[[plugins]]
repo = 'prabirshrestha/asyncomplete.vim'
# on_ft = ['autohotkey', 'autoit', 'cfg', 'git', 'go', 'groovy', 'java', 'javascript', 'python', 'snippet', 'toml', 'vim', 'vb', 'xsl']
# hook_add = '''
#   " let g:asyncomplete_log_file = expand('~/.vim/.asyncomplete/log.log')
#   let g:asyncomplete_enable_for_all = 0
#   autocmd completion FileType autohotkey,autoit,cfg,git,go,groovy,java,javascript,python,snippet,toml,vim,vb,xsl call asyncomplete#enable_for_buffer()
# '''

[[plugins]]
repo = 'prabirshrestha/asyncomplete-buffer.vim'
# on_ft = ['autohotkey', 'autoit', 'cfg', 'git', 'go', 'groovy', 'java', 'javascript', 'python', 'snippet', 'toml', 'vim', 'vb', 'xsl']
# hook_source = '''
#   autocmd completion User asyncomplete_setup call asyncomplete#register_source(asyncomplete#sources#buffer#get_source_options({
#      \ 'name': 'buffer',
#      \ 'priority': 5,
#      \ 'whitelist': ['*'],
#      \ 'completor': function('asyncomplete#sources#buffer#completor'),
#      \ }))
# '''

[[plugins]]
repo = 'prabirshrestha/asyncomplete-file.vim'
# on_ft = ['autohotkey', 'autoit', 'cfg', 'git', 'go', 'groovy', 'java', 'javascript', 'python', 'snippet', 'toml', 'vim', 'vb', 'xsl']
# hook_source = '''
#   autocmd completion User asyncomplete_setup call asyncomplete#register_source(asyncomplete#sources#file#get_source_options({
#       \ 'name': 'file',
#       \ 'priority': 3,
#       \ 'whitelist': ['*'],
#       \ 'completor': function('asyncomplete#sources#file#completor'),
#       \ }))
# '''

[[plugins]]
repo = 'prabirshrestha/asyncomplete-lsp.vim'
on_ft = ['python', 'go']
depends = ['asyncomplete.vim', 'vim-lsp']

[[plugins]]
repo = 'prabirshrestha/vim-lsp'
# hook_add = '''
#   if executable('pyls')
#     autocmd completion User lsp_setup call lsp#register_server({
#         \ 'name': 'pyls',
#         \ 'cmd': {server_info->['pyls']},
#         \ 'whitelist': ['python'],
#         \ })
#   endif
#   if executable('go-langserver')
#     au User lsp_setup call lsp#register_server({
#         \ 'name': 'go-langserver',
#         \ 'cmd': {server_info->['go-langserver', '-gocodecompletion']},
#         \ 'whitelist': ['go'],
#         \ })
#    endif
# '''

[[plugins]]
repo = 'mattn/vim-lsp-settings'

[[plugins]]
repo = 'mattn/vim-lsp-icons'

[[plugins]]
repo = 'hrsh7th/vim-vsnip'

[[plugins]]
repo = 'hrsh7th/vim-vsnip-integ'
# --
