[[plugins]]
repo = 'Shougo/dein.vim'

# カーソル位置のコンテキストに合わせてftを切り替える -- 重すぎるので無効化
#[[plugins]]
#repo = 'osyo-manga/vim-precious'
#depends = ['context_filetype.vim']

[[plugins]] # カーソル位置のコンテキストのftを判定するライブラリ
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'delphinus35/typescript-vim'
rev  = 'colorize-template-strings'

[[plugins]]
repo = 'kchmck/vim-coffee-script'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'elzr/vim-json'
if   = '''! has('kaoriya')'''

[[plugins]]
repo = 'simeji/winresizer'
hook_source = '''
  let g:winresizer_start_key=''
  let g:winresizer_gui_start_key=''
  let g:winresizer_vert_resize=5
  let g:winresizer_horiz_resize=2
'''

[[plugins]]
repo = 'Shougo/vinarise'

[[plugins]]
repo = 'kshenoy/vim-signature'

[[plugins]]
repo = 'majutsushi/tagbar'

[[plugins]]
repo = 'kana/vim-operator-user'

[[plugins]]
repo = 'rhysd/vim-operator-surround'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'rhysd/committia.vim'
hook_source = '''
	let g:committia_open_only_vim_starting = 1
	let g:committia_hooks = {}
	function! g:committia_hooks.edit_open(info)
	    " Additional settings
	    setlocal spell

	    " If no commit message, start with insert mode
	    if a:info.vcs ==# 'git' && getline(1) ==# ''
	        startinsert
	    end

	    " Scroll the diff window from insert mode
	    " Map <C-n> and <C-p>
	    imap <buffer><C-n> <Plug>(committia-scroll-diff-down-half)
	    imap <buffer><C-p> <Plug>(committia-scroll-diff-up-half)

	endfunction
'''

[[plugins]]
repo = 'mhinz/vim-signify'

[[plugins]]
repo = 'sheerun/vim-wombat-scheme'

[[plugins]]
repo = 'b4b4r07/solarized.vim'

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
  let g:lightline = {
        \ 'colorscheme': 'wombat',
        \ 'active': {
        \   'left': [ [ 'mode', 'paste' ],
        \             [ 'gitbranch', 'readonly', 'filename', 'modified' ] ]
        \ },
        \ 'component_function': {
        \   'gitbranch': 'fugitive#head'
        \ },
        \ }
'''
hook_source = '''
  augroup ReloadLL
    autocmd BufRead,BufNewFile * call lightline#colorscheme()
  augroup END
'''

[[plugins]]
repo = 'itchyny/vim-gitbranch'

[[plugins]]
repo = 'ujihisa/neco-look'

[[plugins]]
repo = 'Konfekt/FastFold'

[[plugins]]
repo = 'b4b4r07/vim-ansible-vault'

