[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'
hook_add='''
inoremap <silent><expr> <TAB>
      \ pumvisible() ? "\<C-n>" :
      \ <SID>check_back_space() ? "\<TAB>" :
      \ coc#refresh()
inoremap <expr><Tab> pumvisible() ? "\<C-n>" : "\<Tab>"
inoremap <expr><S-TAB> pumvisible() ? "\<C-p>" : "\<C-h>"
function! s:check_back_space() abort
  let col = col('.') - 1
  return !col || getline('.')[col - 1]  =~# '\s'
endfunction

nmap <silent> gd <Plug>(coc-definition)
nmap <silent> gy <Plug>(coc-type-definition)
nmap <silent> gi <Plug>(coc-implementation)
nmap <silent> gr <Plug>(coc-references)
'''

[[plugins]]
repo = 'theoldmoon0602/coc-plug'
hook_add='''
" Coc Plugin management
call coc_plug#begin()
  CocPlug 'coc-python'
  CocPlug 'coc-sh'
  CocPlug 'coc-yaml'
  CocPlug 'coc-rust-analyzer'
  CocPlug 'coc-docker'
  CocPlug 'coc-vimlsp'
call coc_plug#end()
'''
