#!/bin/bash

set -eu

srcPjDir=$1
dstPjDir=$2

if [[ ! -d "$srcPjDir" ]]; then
  echo "error: invalid src pj dir"
  exit 1
fi

if [[ ! -d "$dstPjDir" ]]; then
  echo "error: invalid dst pj dir"
  exit 1
fi

srcPjDir=$(echo "$srcPjDir" | sed 's/\/$//')
dstPjDir=$(echo "$dstPjDir" | sed 's/\/$//')

pushd "$dstPjDir" || exit
terraform init
terraform state pull > tfstate
popd || exit

pushd "$srcPjDir" || exit
terraform init
terraform state pull > tfstate
popd || exit

pushd "$srcPjDir" || exit
tgtFiles=$(find -- *.tf | peco --prompt "select target files")
popd || exit

for tgt in $tgtFiles; do
  for rsc in $(list-tf-resources "${srcPjDir}/$tgt"); do
    echo terraform state mv -state="${srcPjDir}"/tfstate -state-out="${dstPjDir}"/tfstate "$rsc" "$rsc"
    terraform state mv -state="${srcPjDir}"/tfstate -state-out="${dstPjDir}"/tfstate "$rsc" "$rsc"
  done
done
