#!/bin/bash
#
#
set -eu

function usage {
  echo "Usage: $1 [-y]"
}

function mv_blocks {
  local from=$1
  local to=$2
  local type=$3

  blk=$(hcledit block get "$type" < "$from")
  if [[ -n $blk ]]; then
    printf "%s\n\n" "$blk" >> "$to"
    hcledit block rm "$type" --update --file "$from"
  fi

}

locals_file_tmp=_locals_tf
locals_file=locals.tf

vars_file_tmp=_variables_tf
vars_file=variables.tf

outputs_file_tmp=_outputs_tf
outputs_file=outputs.tf

provider_file_tmp=_provider_tf
provider_file=provider.tf

moved_file_tmp=_moved_tf
moved_file=moved.tf

rm -f $locals_file_tmp
rm -f $vars_file_tmp
rm -f $outputs_file_tmp
rm -f $provider_file_tmp
rm -f $moved_file_tmp

while getopts h flag
do
    case "${flag}" in
        h) usage "$0"; exit 0;;
        *) usage "$0"; exit 0;;
    esac
done

# classify
for f in *.tf; do
  echo "Processing $f"

  while read -r d; do
    case "${d}" in
      locals)
        mv_blocks "$f" "$locals_file_tmp" "$d"
        ;;
      data.terraform_remote_state*)
        mv_blocks "$f" "$vars_file_tmp" "$d"
        ;;
      variable*)
        mv_blocks "$f" "$vars_file_tmp" "$d"
        ;;
      output*)
        mv_blocks "$f" "$outputs_file_tmp" "$d"
        ;;
      terraform*|provider*)
        mv_blocks "$f" "$provider_file_tmp" "$d"
        ;;
      moved*)
        mv_blocks "$f" "$moved_file_tmp" "$d"
        ;;
      *)
        ;;
    esac
  done < <(hcledit block list < "$f")
done

[[ -f $locals_file_tmp ]] && mv $locals_file_tmp $locals_file && gsed -i '${/$/d;}' $locals_file
[[ -f $vars_file_tmp ]] && mv $vars_file_tmp $vars_file && gsed -i '${/$/d;}' $vars_file
[[ -f $outputs_file_tmp ]] && mv $outputs_file_tmp $outputs_file && gsed -i '${/$/d;}' $outputs_file
[[ -f $provider_file_tmp ]] && mv $provider_file_tmp $provider_file  && gsed -i '${/$/d;}' $provider_file
[[ -f $moved_file_tmp ]] && mv $moved_file_tmp $moved_file && gsed -i '${/$/d;}' $moved_file

# cleanup
for f in *.tf; do
  if [[ $(hcledit block list < "$f" | wc -l) -eq 0 ]]; then
    rm "$f"
    continue;
  fi
done

set +eu
terraform fmt
tflint --fix
set -eu

echo "Complete"
