#!/bin/bash
#
#
set -eu

function usage {
  echo "Usage: $1 [-y] [-p <pattern_file>]"
  echo "  -y: dry run"
  echo "  -p: pattern file"
}

function get_rsc_type {
  rsc_name=$1
  rsc_type="misc"

  case $rsc_name in
    *security_group* ) rsc_type="sg" ;;
    *route53* ) rsc_type="route53" ;;
    *waf* ) rsc_type="waf" ;;
    *kms* ) rsc_type="kms" ;;
    *secretmanager* ) rsc_type="secret" ;;
    *secret* ) rsc_type="secret" ;;
    *aws_lb* ) rsc_type="loadbalancer" ;;
    *-alb* ) rsc_type="loadbalancer" ;;
    *-lb* ) rsc_type="loadbalancer" ;;
    *-tg* ) rsc_type="loadbalancer" ;;
    *aws_iam* ) rsc_type="iam" ;;
    *instance-profile* ) rsc_type="iam" ;;
    *-policy* ) rsc_type="iam" ;;
    *-developer* ) rsc_type="iam" ;;
    *aws_db* ) rsc_type="rds" ;;
    *aws_ecr* ) rsc_type="ecr" ;;
    *cluster* ) rsc_type="cluster" ;;
    data* ) rsc_type="data" ;;
    * ) ;;
  esac

  echo $rsc_type
}

function classify {
  local rsc_name=$1
  local tf_file=$2
  local pattern_file=$3

  prefix="_"

  stage=$(echo "$rsc_name" | gsed -e 's/.*\(staging\|production\|development\|integration\|st-\|intg\).*/\1/gp;d')
  if [[ -z $stage ]]; then
    stage=$(hcledit attribute get "$rsc_name.tags" < "$tf_file" | gsed -e 's/.*\(staging\|production\|development\|integration\|st-\|intg\).*/\1/gp;d' | head -1)
  fi
  if [[ -z $stage ]]; then
    stage=$(hcledit attribute get "$rsc_name.stage" < "$tf_file" | sed 's/\"//g')
  fi
  if [[ -z $stage ]]; then
    if [[ -n $pattern_file && -f $pattern_file ]]; then
      while read -r p; do
        k=$(echo "$p" | cut -d',' -f1)
        s=$(echo "$p" | cut -d',' -f2)

        hcledit block get "$rsc_name" < "$tf_file"  | grep -q "$k" && stage=$s && break
      done < "$pattern_file"
    fi
  fi
  if [[ -z $stage ]]; then
    stage="common"
  fi

  rsc_type=$(get_rsc_type $rsc_name)

  echo "$prefix""$stage"-"$rsc_type".tf | sed -e 's/st-/staging/g' -e  's/intg/integration/g'
}

patternFile=""
block_list=_block_list
locals_file=_locals_tf

while getopts yp:h flag
do
    case "${flag}" in
        y) dryRun="false";;
        p) patternFile=${OPTARG};;
        h) usage $0; exit 0;;
    esac
done

printf "locals {\n"  > $locals_file

# classify
for f in *.tf; do
  echo "Processing $f"

  tmp_file="$f"_tmp

  cat "$f" | sed '$ s/^}$/}\n/g'  > $tmp_file
  hcledit block list < "$tmp_file" | grep -e '^module' -e '^data' -e '^resource' | grep -v 'data.terraform_remote_state'| sort | uniq > $block_list

  # aggregate locals definitions
  hcledit block get locals < "$tmp_file"  | sed -e '/^locals/d' -e '/^}/d' >> $locals_file
  hcledit block rm "locals" --update --file $tmp_file

  while read -r rsc; do
    classify $rsc $tmp_file $patternFile
    fname=$(classify $rsc $tmp_file $patternFile)

    echo "$fname <- $rsc"

    cat "$tmp_file" | hcledit block get "$rsc" >> "$fname"
    hcledit block rm "$rsc" --update --file $tmp_file
  done < $block_list

  rm "$f"
  mv "$tmp_file" "$f"
done

printf "\n}\n" >> $locals_file

mv $locals_file _locals.tf

# cleanup

rm "$block_list"

for f in *.tf; do
  if [[ $(hcledit block list < "$f" | wc -l) -eq 0 ]]; then
    rm "$f"
    continue;
  fi

  # rename _file
  if [[ $f == _* ]]; then
    mv "$f" "${f:1}"
  fi
done

terraform fmt -recursive
