#!/bin/bash
#

function get_rsc_type {
  rsc_name=$1
  rsc_type="misc"

  case $rsc_name in
    *security_group* ) rsc_type="sg" ;;
    *route53* ) rsc_type="route53" ;;
    *waf* ) rsc_type="waf" ;;
    *kms* ) rsc_type="kms" ;;
    *secretmanager* ) rsc_type="secret" ;;
    *secret* ) rsc_type="secret" ;;
    *aws_lb* ) rsc_type="loadbalancer" ;;
    *-alb* ) rsc_type="loadbalancer" ;;
    *-lb* ) rsc_type="loadbalancer" ;;
    *-tg* ) rsc_type="loadbalancer" ;;
    *aws_iam* ) rsc_type="iam" ;;
    *instance-profile* ) rsc_type="iam" ;;
    *-policy* ) rsc_type="iam" ;;
    *-developer* ) rsc_type="iam" ;;
    *aws_db* ) rsc_type="rds" ;;
    *aws_ecr* ) rsc_type="ecr" ;;
    *cluster* ) rsc_type="cluster" ;;
    data* ) rsc_type="data" ;;
    * ) ;;
  esac

  echo $rsc_type
}

function classify {
  rsc_name=$1
  file_name=$2

  prefix="_"

  stage=$(echo $rsc_name | gsed -e 's/.*\(staging\|production\|development\|integration\|st-\|intg\).*/\1/gp;d')
  if [[ -z $stage ]]; then
    stage=$(hcledit attribute get "$rsc_name.tags" < "$tmp_file" | gsed -e 's/.*\(staging\|production\|development\|integration\|st-\|intg\).*/\1/gp;d' | head -1)
  fi
  if [[ -z $stage ]]; then
    stage="common"
  fi

  rsc_type=$(get_rsc_type $rsc_name)

  echo "$prefix""$stage"-"$rsc_type".tf | sed -e 's/st-/staging/g' -e  's/intg/integration/g'
}

block_list=_block_list
locals_file=_locals.tf
printf "locals {\n"  > $locals_file

# classify
for f in *.tf; do
  echo "Processing $f"

  tmp_file="$f"_tmp

  cat "$f" | sed '$ s/^}$/}\n/g'  > $tmp_file
  cat "$tmp_file" | hcledit block list | grep -e '^module' -e '^data' -e '^resource' | grep -v 'data.terraform_remote_state'| sort | uniq > $block_list

  # aggregate locals definitions
  cat "$tmp_file" | hcledit block get locals | sed -e '/^locals/d' -e '/^}/d' >> $locals_file
  hcledit block rm "locals" --update --file $tmp_file

  while read -r rsc; do
    fname=$(classify $rsc $tmp_file)

    echo "$fname <- $rsc"

    cat "$tmp_file" | hcledit block get "$rsc" >> "$fname"
    hcledit block rm "$rsc" --update --file $tmp_file
  done < $block_list

  rm "$f"
  mv "$tmp_file" "$f"
done

printf "\n}\n" >> $locals_file

# cleanup

rm "$block_list"

for f in *.tf; do
  if [[ $(hcledit block list < "$f" | wc -l) -eq 0 ]]; then
    rm "$f"
    continue;
  fi

  # rename _file
  if [[ $f == _* ]]; then
    mv "$f" "${f:1}"
  fi
done
