#!/bin/bash

file=$1

if [[ ! -f $file ]]; then
  echo "invaid file name"
  exit 1
fi

# resources
for r in $(hcledit block list -f "$file" | grep "^resource"); do
  echo $r
done


# modules
for m in $(hcledit block list -f "$file" | grep "^module"); do
  echo $m
done
