#!/bin/zsh
#

set -eu

function how_to_use {
    echo "### Usage: $1 [-r]"
    echo "### -r: restore backend from override.tf"

    echo
    echo "### Example of commands to run"
    echo
    echo "terraform state pull > tfstate"
    echo "$1"
    echo "terraform init -reconfigure"
    echo "terraform plan --state=tfstate"
    echo "terraform state mv --state=tfstate --state-out=tfstate2 module.vpc_hoge.aws_vpc.this module.vpc_huga.aws_vpc.this"
    echo "sed -i 's/vpc_hoge/vpc_huga/g' tgtfile"
    echo "terraform plan --state=tfstate2"
    echo "$1 -r"
    echo "terraform state push tfstate2"
    echo "terraform plan"
}

function override_backend {
    cat << EOF > override.tf
terraform {
  backend "local" {
  }
}
EOF
}

function restore_backend_from_override {
    rm -f override.tf
}

restore="false"

while getopts yrh flag
do
    case "${flag}" in
        r) restore="true";;
        h) how_to_use $0;exit 0;;
    esac
done


if [[ $restore == "true" ]]; then
    echo "### Remove override.tf"
    restore_backend_from_override
    exit 0
fi

if [[ ! -f tfstate ]]; then
    echo "### tfstate file must be present"
    echo "### Run the following command to create it"
    echo
    echo "terraform state pull > tfstate"
    echo
    exit 1
fi

override_backend

