#!/bin/zsh
#

use_local_tf="false"

while getopts lh flag
do
    case "${flag}" in
        l) use_local_tf="true";;
        h) how_to_use $0;exit 0;;
    esac
done

prompt_from="移動元のPJを選んでください"
pj_from=$(find . -type d -not -path '*/\.*' -not -path '*/node_modules*' | peco --prompt "$prompt_from")

prompt_to="移動先のPJを選んでください"
pj_to=$(find . -type d -not -path '*/\.*' -not -path '*/node_modules*' | peco --prompt "$prompt_to")

if [ ! -d "$pj_from" ]; then
  echo "移動元のPJが存在しません: $pj_from"
  exit 1
elif [ ! -d "$pj_to" ]; then
  echo "移動先のPJが存在しません: $pj_to"
  exit 1
fi

echo "** $pj_from から $pj_to にリソースを移動させます"

if [ $use_local_tf = "false" ]; then
    echo "** tfstateを取得しています... "
    pushd $pj_from > /dev/null
    terraform init
    if [ $? -ne 0 ]; then
      echo "terraform init failed"
      popd > /dev/null
      exit 1
    fi
    terraform state pull > tfstate
    popd > /dev/null

    pushd $pj_to > /dev/null
    terraform init
    if [ $? -ne 0 ]; then
      echo "terraform init failed"
      popd > /dev/null
      exit 1
    fi
    terraform state pull > tfstate
    popd > /dev/null
else
    if [ ! -f $pj_from/tfstate ]; then
        echo "tfstate fileが$pj_fromにありません"
        exit 1
    fi
    if [ ! -f $pj_to/tfstate ]; then
        echo "tfstate fileが$pj_toにありません"
        exit 1
    fi
fi

p=" 移動対象のリソースを選んでください（複数可）"
tgt_rsc=$(terraform state list -state=${pj_from}/tfstate)
mod=$(echo $tgt_rsc | grep '^module' | cut -d. -f1-2 | uniq)
others=$(echo $tgt_rsc | grep -v '^module')
tgt_rsc=$(echo $mod $others | peco --prompt $p)

echo "** tfstateを移動させます"
# cd $root
for rsc in $tgt_rsc; do
  echo "terraform state mv -state=${pj_from}/tfstate -state-out=${pj_to}/tfstate $rsc $rsc"
  terraform state mv -state=${pj_from}/tfstate -state-out=${pj_to}/tfstate $rsc $rsc
done

# echo "** local tfstateをチェックしています..." # remote state使っている場合は`-state` option無視されるらしく使えなさそうなので一旦コメントアウト
# cd $pj_from
# terraform plan -state=tfstate
# cd $root
# cd $pj_to
# terraform plan -state=tfstate
# cd $root

echo "** tfstateの移動が完了しました"
echo "** 次にやること: 1. コードの修正、2. 各PJで terraform state push tfstate、3. planでno diff確認"
