#!/bin/zsh
#
# awslogin: aws login utility, which provides a method to switch between onelogin and iam
#

#set -xeu

cred_file=~/.aws/credentials
prof_file=~/.zshrc.aws.local
default_session_duration=10800

function gen_prof_name()
{
    local arn=$1
    local acc_alias=$(echo $2 | sed -e 's/freee-//' -e 's/finance-lab/ffl/')
    local acc=$(echo $arn | cut -d: -f5)
    local role=$(echo $arn | cut -d/ -f 2 | sed -e 's/freee-//' -e 's/sso-//')
    local h=$(echo $acc | head -c3)
    local t=$(echo $acc | tail -c2)
    echo "${h}*${t}:${acc_alias}:$role"
}

function create_new_prof()
{
    if saml2aws login --skip-prompt --profile=tmp-prof --session-duration=$default_session_duration; then
        local arn=$(aws sts get-caller-identity --profile tmp-prof | jq -r .Arn)
        local acc_alias=$(aws iam list-account-aliases --profile tmp-prof | jq -r '.AccountAliases[]' | head -1)
        local prof=$(gen_prof_name $arn $acc_alias)
        ${curdir}/awsprof-utils/clean-prof $prof # rm old prof if exists
        gsed -i "s/tmp-prof/$prof/" $cred_file
        update_prof_file $prof_file $prof
        ${curdir}/awsprof-utils/create-saml2aws-prof $prof
    else
        echo "fail to login"
    fi
}

function switch_prof()
{
    prof=$1
    update_prof_file $prof_file $prof
}

function update_prof()
{
    local prof=$1
    local opt="--profile=$prof"
    if grep -F $prof ~/.saml2aws; then
        if saml2aws login --skip-prompt -a "$prof"; then
            arn=$(aws sts get-caller-identity --profile $prof | jq -r .Arn)
            update_prof_file $prof_file $prof
        else
            echo "fail to login"
        fi
    else
        create_new_prof
    fi
}

function update_prof_file()
{
    if [ $# -lt 2 ]; then
        echo 'error'
    else
        local prof_file=$1
        local prof=$2
        local alias=$2

        echo > $prof_file

        echo "unset AWS_ACCESS_KEY_ID" >> $prof_file
        echo "unset AWS_SECRET_ACCESS_KEY" >> $prof_file
        echo "export AWS_ENABLE_USER=0" >> $prof_file
        echo "export AWS_DEFAULT_PROFILE=$prof" >> $prof_file
        echo "export AWS_PROFILE=$prof" >> $prof_file
        echo "export AWS_DEFAULT_REGION=ap-northeast-1" >> $prof_file
        echo "export AWS_PROFILE_ALIAS=$alias" >> $prof_file
    fi
}

curdir=$(cd $(dirname $0);pwd)

profs=$(${curdir}/awsprof-utils/ls-prof)

select=$(echo "NewProf\n$profs" | column -t -s, | peco)

if [[ -z $select ]]; then
    exit 0
fi

if [[ $select == "NewProf" ]]; then
    create_new_prof
else
    expired_at=$(echo $select | awk '{print $3}')
    prof_name=$(echo $select | awk '{print $1}')

    if [[ $expired_at != "expired" ]]; then
        switch_prof $prof_name
    else
        # ${curdir}/awsprof-utils/clean-prof $prof_name
        update_prof $prof_name
    fi
fi
