#!/bin/sh
#
# issh: wrapper for lshost providing interactive ssh
#

#set -xeu
set -u

function usage()
{
	echo "usage: $1 [options]"
	echo "	-h         print this usage and exit"
	echo "	-f         set filter for lshost"
	echo "	-u         update host cache file"

}

filter=""
update=0
bname=`basename $0`

lshost=lsaws

while getopts urf:h OPT;
do
	case $OPT in
		"f") filter="$OPTARG";;
		"u") update=1;;
		"h") usage ${bname}; exit;;
	esac
done

if [ ! -x "`which ${lshost} 2> /dev/null`" ]; then
	echo "error: ${lshost} not found" >&2
	exit 1
fi

if [ ! -x "`which peco 2> /dev/null`" ]; then
	echo "error: peco not found" >&2
	exit 1
fi

if [ $update = 1 ]; then
	tgt_server=$(${lshost} -u -l ${filter} | peco)
else
	tgt_server=$(${lshost} -l ${filter} | peco)
fi

ipaddr=$(echo ${tgt_server} | sed 's/^.* \(10\.[0-9]*\.[0-9]*\.[0-9]*\) .*$/\1/')

if [ $? -eq 0 -a "${ipaddr}" != "" ]; then
	echo "** [${bname}] target: ${tgt_server}"
	if [ -x "`which sshrc 2> /dev/null`" ]; then
		echo "** [${bname}] sshrc to: ${ipaddr}"
		sshrc ${ipaddr}
	else
		echo "** [${bname}] ssh to: ${ipaddr}"
		ssh ${ipaddr}
	fi
fi
