#!/bin/sh
#
# wrapper for lshost
#

#set -xeu
set -u

ONELOGIN_EXPIRED_SEC=3600
CACHE_EXPIRED_SEC=600

function usage()
{
	echo "usage: $1 [options]"
	echo "	-h         print this usage and exit"
	echo "	-f         set filter for lshost"
	echo "	-r         force re-login to onelogin"
	echo "	-u         update host cache file"

}

filter=""
relogin=0
update=0
bname=`basename $0`

while getopts urf:h OPT;
do
	case $OPT in
		"f") filter="$OPTARG";;
		"r") relogin=1;;
		"u") update=1;;
		"h") usage ${bname}; exit;;
	esac
done

hosts_base=~/.cache/awshosts
rcfile=~/.zshrc.local

if [ ! -x "`which lshost 2> /dev/null`" ]; then
	echo "error: lshost not found" >&2
	exit 1
fi

if [ ! -x "`which peco 2> /dev/null`" ]; then
	echo "error: peco not found" >&2
	exit 1
fi

eval $(stat -s $rcfile)
mtime=${st_mtime}
ctime=$(date +%s)
laps=$(echo "$ctime - $mtime" | bc)

if [ $laps -gt $ONELOGIN_EXPIRED_SEC -a ${relogin} != 1 ]; then
	echo "** [${bname}] warning: onelogin may be expired."

	while true;do
		echo "re-login? [y/n]"
		read ans
		case $ans in
			y) relogin=1; break;;
			n) relogin=0; break;;
			*) ;;
		esac
	done
fi

if [ $relogin = 1 ]; then
	onelogin
	echo "** [${bname}] retry after exec \"source ${rcfile}\""
	exit 0
fi

source ${rcfile}

if [ $update = 1 ]; then
	tgt_server=$(lshost -u -l ${filter} | peco)
else
	tgt_server=$(lshost -l ${filter} | peco)
fi

ipaddr=$(echo ${tgt_server} | sed 's/^.* \(10\.[0-9]*\.[0-9]*\.[0-9]*\) .*$/\1/')

if [ $? -eq 0 -a "${ipaddr}" != "" ]; then
	echo "** [${bname}] target: ${tgt_server}"
	if [ -x "`which sshrc 2> /dev/null`" ]; then
		echo "** [${bname}] sshrc to: ${ipaddr}"
		sshrc ${ipaddr}
	else
		echo "** [${bname}] ssh to: ${ipaddr}"
		ssh ${ipaddr}
	fi
fi
