#!/bin/sh
#
# wrapper for onelogin-aws-login
#

#set -xeu

# mkfifo tmp_pipe
# cat <tmp_pipe &

rcfile=~/.zshrc.local

unset AWS_DEFAULT_PROFILE

output=$(expect -c "
set timeout 5

spawn onelogin-aws-login

expect {
	\"Onelogin Username:\" {
		send \"akawamura@c-fo.com\n\"
	}
}

expect {
	-glob \"Onelogin Password:\" {
		interact
		exit 0
	}
}
" | tee /dev/stderr)

if [ $? != 0 ]; then
	exit 1
fi

# rm tmp_pipe
profile=$(echo $output | sed 's/^.*profile \(.*\)$/\1/' | sed 's///')

case ${OSTYPE} in
	cygwin|linux*) sed -i "s:FILE=\(.*\)$:FILE="$profile":" ${rcfile} ;;
	darwin*) sed -i "" "s:FILE=\(.*\)$:FILE="$profile":" ${rcfile} ;;
esac

echo "  login success! please exec \"soure ${rcfile}\" on your terminal"

