#!/bin/sh
#
# git-set-config: set local gitconfig for corp repos
#

rep_name=$(basename `git remote get-url origin`)
org_name=C-FO

git remote add upstream git://github.com/${org_name}/${rep_name}.git
git remote set-url --push upstream no_push
git remote add pr git://github.com/${org_name}/${rep_name}.git
git config remote.pr.fetch '+refs/pull/*:refs/remotes/pr/*'
