[character]
success_symbol = "[➜](bold green)"
error_symbol = "[✗](bold red)"
#use_symbol_for_status = true
#
[aws]
disabled = true

[kubernetes]
format = '[⛵ $context \($namespace\)](bold green) '
disabled = false

[kubernetes.context_aliases]
"arn:aws:eks:ap-northeast-1:057575985710:cluster/infra-test-env-1" = "infra-test-env-1"
"arn:aws:eks:ap-northeast-1:057575985710:cluster/integration-benefit-1" = "integration-benefit-1"
"arn:aws:eks:ap-northeast-1:057575985710:cluster/integration-coreengine-2" = "integration-coreengine-2"
"arn:aws:eks:ap-northeast-1:057575985710:cluster/integration-deal-platform-1" = "integration-deal-platform-1"
"arn:aws:eks:ap-northeast-1:057575985710:cluster/integration-ebis-1" = "integration-ebis-1"
"arn:aws:eks:ap-northeast-1:057575985710:cluster/integration-freee-ctax-1" = "integration-freee-ctax-1"
"arn:aws:eks:ap-northeast-1:057575985710:cluster/integration-freee-payroll-2" = "integration-freee-payroll-2"
"arn:aws:eks:ap-northeast-1:057575985710:cluster/integration-growth-1" = "integration-growth-1"
"arn:aws:eks:ap-northeast-1:057575985710:cluster/integration-javelin-3" = "integration-javelin-3"
"arn:aws:eks:ap-northeast-1:057575985710:cluster/integration-nest-auth-1" = "integration-nest-auth-1"
"arn:aws:eks:ap-northeast-1:057575985710:cluster/integration-ohmu-4" = "integration-ohmu-4"
"arn:aws:eks:ap-northeast-1:057575985710:cluster/integration-wolf-2" = "integration-wolf-2"
"arn:aws:eks:ap-northeast-1:057575985710:cluster/kubeflow-1" = "kubeflow-1"
"arn:aws:eks:ap-northeast-1:057575985710:cluster/production-ai-lab-3" = "production-ai-lab-3"
"arn:aws:eks:ap-northeast-1:057575985710:cluster/production-benefit-2" = "production-benefit-2"
"arn:aws:eks:ap-northeast-1:057575985710:cluster/production-containerkojo-3" = "production-containerkojo-3"
"arn:aws:eks:ap-northeast-1:057575985710:cluster/production-coreengine-1" = "production-coreengine-1"
"arn:aws:eks:ap-northeast-1:057575985710:cluster/production-coreengine-2" = "production-coreengine-2"
"arn:aws:eks:ap-northeast-1:057575985710:cluster/production-deal-platform-2" = "production-deal-platform-2"
"arn:aws:eks:ap-northeast-1:057575985710:cluster/production-ebis-2" = "production-ebis-2"
"arn:aws:eks:ap-northeast-1:057575985710:cluster/production-freee-ctax-1" = "production-freee-ctax-1"
"arn:aws:eks:ap-northeast-1:057575985710:cluster/production-freee-payroll-2" = "production-freee-payroll-2"
"arn:aws:eks:ap-northeast-1:057575985710:cluster/production-goat-3" = "production-goat-3"
"arn:aws:eks:ap-northeast-1:057575985710:cluster/production-growth-2" = "production-growth-2"
"arn:aws:eks:ap-northeast-1:057575985710:cluster/production-haisocenter-1" = "production-haisocenter-1"
"arn:aws:eks:ap-northeast-1:057575985710:cluster/production-javelin-4" = "production-javelin-4"
"arn:aws:eks:ap-northeast-1:057575985710:cluster/production-jigsaw-3" = "production-jigsaw-3"
"arn:aws:eks:ap-northeast-1:057575985710:cluster/production-nest-auth-3" = "production-nest-auth-3"
"arn:aws:eks:ap-northeast-1:057575985710:cluster/production-ohmu-3" = "production-ohmu-3"
"arn:aws:eks:ap-northeast-1:057575985710:cluster/production-sre-2" = "production-sre-2"
"arn:aws:eks:ap-northeast-1:057575985710:cluster/production-wolf-3" = "production-wolf-3"
"arn:aws:eks:ap-northeast-1:057575985710:cluster/staging-ai-lab-3" = "staging-ai-lab-3"
"arn:aws:eks:ap-northeast-1:057575985710:cluster/staging-ainori-1" = "staging-ainori-1"
"arn:aws:eks:ap-northeast-1:057575985710:cluster/staging-benefit-2" = "staging-benefit-2"
"arn:aws:eks:ap-northeast-1:057575985710:cluster/staging-cilium-growth-1" = "staging-cilium-growth-1"
"arn:aws:eks:ap-northeast-1:057575985710:cluster/staging-clusterupdate-1" = "staging-clusterupdate-1"
"arn:aws:eks:ap-northeast-1:057575985710:cluster/staging-containerkojo-2" = "staging-containerkojo-2"
"arn:aws:eks:ap-northeast-1:057575985710:cluster/staging-coreengine-1" = "staging-coreengine-1"
"arn:aws:eks:ap-northeast-1:057575985710:cluster/staging-csirt-cluster-2" = "staging-csirt-cluster-2"
"arn:aws:eks:ap-northeast-1:057575985710:cluster/staging-deal-platform-2" = "staging-deal-platform-2"
"arn:aws:eks:ap-northeast-1:057575985710:cluster/staging-ebis-2" = "staging-ebis-2"
"arn:aws:eks:ap-northeast-1:057575985710:cluster/staging-freee-ctax-1" = "staging-freee-ctax-1"
"arn:aws:eks:ap-northeast-1:057575985710:cluster/staging-freee-payroll-2" = "staging-freee-payroll-2"
"arn:aws:eks:ap-northeast-1:057575985710:cluster/staging-goat-3" = "staging-goat-3"
"arn:aws:eks:ap-northeast-1:057575985710:cluster/staging-growth-2" = "staging-growth-2"
"arn:aws:eks:ap-northeast-1:057575985710:cluster/staging-haisocenter-1" = "staging-haisocenter-1"
"arn:aws:eks:ap-northeast-1:057575985710:cluster/staging-javelin-4" = "staging-javelin-4"
"arn:aws:eks:ap-northeast-1:057575985710:cluster/staging-jigsaw-3" = "staging-jigsaw-3"
"arn:aws:eks:ap-northeast-1:057575985710:cluster/staging-nest-auth-3" = "staging-nest-auth-3"
"arn:aws:eks:ap-northeast-1:057575985710:cluster/staging-ohmu-3" = "staging-ohmu-3"
"arn:aws:eks:ap-northeast-1:057575985710:cluster/staging-sre-1" = "staging-sre-1"
"arn:aws:eks:ap-northeast-1:057575985710:cluster/staging-wolf-3" = "staging-wolf-3"
"arn:aws:eks:ap-northeast-1:057575985710:cluster/test-sre-1" = "test-sre-1"
