#!/bin/zsh
# clean-prof
#   remove expired profiles

cred=~/.aws/credentials
cred_tmp=~/.aws/credentials_tmp

function filter_prof()
{
    local tgt_prof=$1
    local crd_file=$2
    local toggle=0

    if [[ ! -f $crd_file ]]; then
        echo "no cred file"; exit 0
    fi


    while read line; do
        if [[ $line == \[*] ]]; then
            prof=$(echo $line | sed 's/\[\(.*\)\]/\1/')
            if [[ $prof == $tgt_prof ]]; then
                toggle=1
            else
                toggle=0
            fi
        fi

        if [[ $toggle == 0 ]]; then
            echo $line
        fi
    done < $crd_file
}

if [[ $# != 1 ]]; then
    exit 0
fi

filter_prof $1 $cred > $cred_tmp
mv $cred_tmp $cred
