#!/bin/zsh
# ls-prof
#   list all aws profiles

# clear profile
# echo > ~/.aws/credentials

function remain_sec()
{
    local expired_at=$(gdate --date $1 +"%s")
    local current=$(gdate +"%s")
    local remain_sec=$(($expired_at - $current))
    if [ $remain_sec -lt 0 ]; then
        # remain_sec="\e[31mexpired\e[m"
        remain_sec="expired"
    elif [ $remain_sec -lt 600 ]; then
        # remain_sec="\e[33m$remain_sec\e[m"
    else
        # remain_sec="\e[32m$remain_sec\e[m"
    fi
    echo $remain_sec
}

function print_prof()
{
    if [[ $# != 3 ]]; then
        echo "no prof"
        return
    fi
    local prof=$1
    local arn=$2
    local expired_at=$3
    local exp=$(remain_sec $expired_at)

    local acc=$(echo $arn | cut -d':' -f 5)
    local role=$(echo $arn | cut -d'/' -f 2)
    # echo "$prof,$acc/$role,$exp" | column -t -s,
    echo "$prof,$acc/$role,$exp"
}

function get_from_credfile()
{
    local cred=~/.aws/credentials

    if [[ ! -f $cred ]]; then
        echo "no cred file"; exit 0
    fi

    local prof=""; local arn=""; local exp=""

    while IFS=' = ' read var val; do
        if [[ $var == \[*] ]]; then
            if [[ "$prof" != "" ]]; then
                print_prof $prof $arn $exp
                arn="";exp="";
            fi
            prof=$(echo $var | sed 's/\[\(.*\)\]/\1/')
        elif [[ $var == x_principal_arn ]]; then
            arn=$val
        elif [[ $var == x_security_token_expires ]]; then
            exp=$val
        fi
    done < $cred
    print_prof $prof $arn $exp
}

function get_from_api()
{
    local exp=""
    local arn=""
    for prof in `aws configure list-profiles`; do
        exp=$(aws configure get x_security_token_expires --profile $prof)
        [[ -z $exp ]] && continue

        arn=$(aws configure get x_principal_arn --profile $prof)

        print_prof $prof $arn $exp
    done
}

print_current=0
while getopts r:c OPT;
do
	case $OPT in
		"c") print_current=1;;
	esac
done

if [[ $print_current == 0 ]]; then
    # get_from_api
    get_from_credfile
else
    get_from_credfile | grep -F $AWS_PROFILE
fi
